### ISSUE TITLE
Does not support extraction of multiple fields

### ISSUE THREAD

**Issue by chrisptree** [mesarth/JSONPath-Notebook#19]
When I try to execute the following query upon the attached file:
$[?(@.source=='ext')].[name, rootdir]

I got this error
unexpected shorthand selector '[' ('')].[@.ro':22)

[plugins-list.json](https://github.com/user-attachments/files/17738374/plugins-list.json)

**Comment by mesarth** [comment]
Not sure exactly what you’re aiming for with your query, but you might just need a small tweak to get it working. Try this format instead: `$[?(@.source=='ext')]['name','rootdir']`

**Comment by chrisptree** [comment]
I tried what you suggest, but it didn't give me the result I want. I want an ouput like this:
```json
[
  {
    "name": "customcert",
    "rootdir": "/local/pedagogie/http-data/deployer/fi-mig.teluq.ca/releases/2/mod/customcert"
  },
  {
    "name": "hvp",
    "rootdir": "/local/pedagogie/http-data/deployer/fi-mig.teluq.ca/releases/2/mod/hvp"
  }
]
```

**Comment by mesarth** [comment]
As far as I know, what you are trying to achieve is not possible with JSONPath. JSONPath is designed to select values and not key-value pairs. I would use a scripting language like JavaScript for this.
